### ISSUE TITLE
Installation problems with fastparquet, swifter, gensim

### ISSUE THREAD

**Issue by apolo74** [severian42/GraphRAG-Ollama-UI#12]
Hello, I'm working under Windows with VSCode. I created a new virtual environment with Python 3.12.3. When running the '*pip install -r requirements.txt*', everything was going smoothly until this point where I get a huge list of errors that start with the following:

```bash
Building wheels for collected packages: fastparquet, swifter, gensim
  Building wheel for fastparquet (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for fastparquet (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [140 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
      Traceback (most recent call last):
        File "C:\Users\bduran\AppData\Local\Temp\pip-build-env-s3y_b9ux\overlay\Lib\site-packages\setuptools_scm\_integration\pyproject_reading.py", line 36, in read_pyproject
          section = defn.get("tool", {})[tool_name]
                    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
      KeyError: 'setuptools_scm'
      running bdist_wheel
      running build
```

Any ideas how to solve this?

**Comment by apolo74** [comment]
It seems that GraphRAG does not work with Python 3.12. I switched to Python 3.11 and I also changed the version requirement for *gradio*... from ```gradio>=latest``` to just ```gradio```. The repository is installed without problems after that.

**Comment by severian42** [comment]
Ah!! Thanks so much for catching this. I was in the middle of finally getting back to you, sorry for the delayed response. Trying to get the new update finished. I run everything on a Mac Studio so I'm not as well versed in troubleshooting Windows issues. I made an update to the .txt with the change you suggested, many thanks again!
