### ISSUE TITLE
v0.09: Indexing does not start. AttributeError: 'Blocks' object has no attribute '_queue'

### ISSUE THREAD

**Issue by alba49** [severian42/GraphRAG-Ollama-UI#13]
After update to the new release v0.09 the indexing does not start. 
Installation was with: git clone https://github.com/severian42/GraphRAG-Ollama-UI.git 
With the previous Version 'Run Indexing'  worked as expected.

The error is:

Traceback (most recent call last):
  File "/home/abc/anaconda3/envs/graphui/lib/python3.11/site-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abc/anaconda3/envs/graphui/lib/python3.11/site-packages/gradio/blocks.py", line 1384, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abc/anaconda3/envs/graphui/lib/python3.11/site-packages/gradio/blocks.py", line 1081, in call_function
    progress_tracker, fn = create_tracker(
                           ^^^^^^^^^^^^^^^
  File "/home/abc/anaconda3/envs/graphui/lib/python3.11/site-packages/gradio/helpers.py", line 545, in create_tracker
    progress = Progress(_callback=root_blocks._queue.set_progress, _event_id=event_id)
                                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'Blocks' object has no attribute '_queue'

**Comment by severian42** [comment]
Sorry about that, the queue got dropped somehow with the last versioning before the push. I just updated with the correct Gradio call for the demo and queue to use. The indexing relies on the queuing to make everything function properly. The changes were only made to the `app.py` script so you can just copy/paste the newest edit and its should launch for you

**Comment by severian42** [comment]
The error has to do with the Gradio version, you may need to run `pip install --upgrade gradio' then exit out and restart the env to launch the app. I had to do this on my machine when first troubleshooting and it solved the issue. I may need to find a better process other than relying on Gradio's queue but for now it's a great hack. If that doesn't solve it for you I may need to make a version that uses an older more stable version of Gradio

**Comment by alba49** [comment]
I can confirm that now the error is solved, indexing is working.

I can also confirm (with one run) that all three queries: global, local and direct work and 20 files where created. Same for .graphml visualisations.

Perfect.
