### ISSUE TITLE
ModuleNotFound Error : No Module names Azure

### ISSUE THREAD

**Issue by fahdmirza** [severian42/GraphRAG-Ollama-UI#2]
Hi,
  I am trying to review this tool for my channel at https://www.youtube.com/@fahdmirza and facing multiple errors. Could we please connect as I am in middle of creating video and would appreciate the resolution please. Thanks.

**Comment by fahdmirza** [comment]
Hi,
  Just to let you know the steps, I have git cloned your repo, installed requirements , ollama is already running at default port with mistral 7b and nomic-embed models, and then I have launched gradio app. 

In browser, first I have uploaded a text file in Data Management tab and then indexed it. All good so far. I don't see anything in Indexing outputs tab though. When I run a query , it gives me error Module Not FoundError: No module named 'azure'

**Comment by fahdmirza** [comment]
ok I was able to fix above error by manually installing pip install graphrag. Also global search works, local search is not working with this tool. Thanks

**Comment by severian42** [comment]
Hey! Thanks so much for checking this out and creating the issue. I somehow forgot to add the graphrag install in the requirements.txt when packaging this all together, it was a long night. Thank you for catching that! For the azure, I tried to clean out any dependencies for it but there might be one or two left in the imprts for me to dig out from the original Microsoft code. I am also working on fixing the local search to get it working again, it has been a bit finicky.

**Comment by severian42** [comment]
Local search should work now. I updated the embeddings.py in the graphrag dir to handle the dim correctly! Just paste in the new embeddings.py in the query dir and you should be good to go!

```shell
INFO: Reading settings from ragtest/settings.yaml
creating llm client with {'api_key': 'REDACTED,len=9', 'type': "openai_chat", 'model': 'mistral:7b', 'max_tokens': 4000, 'temperature': 0.0, 'top_p': 1.0, 'request_timeout': 180.0, 'api_base': 'http://localhost:11434/v1', 'api_version': None, 'organization': None, 'proxy': None, 'cognitive_services_endpoint': None, 'deployment_name': None, 'model_supports_json': True, 'tokens_per_minute': 0, 'requests_per_minute': 0, 'max_retries': 10, 'max_retry_wait': 10.0, 'sleep_on_rate_limit_recommendation': True, 'concurrent_requests': 10}
creating embedding llm client with {'api_key': 'REDACTED,len=9', 'type': "openai_embedding", 'model': 'nomic_embed_text', 'max_tokens': 4000, 'temperature': 0, 'top_p': 1, 'request_timeout': 180.0, 'api_base': 'http://localhost:11434/v1', 'api_version': None, 'organization': None, 'proxy': None, 'cognitive_services_endpoint': None, 'deployment_name': None, 'model_supports_json': None, 'tokens_per_minute': 0, 'requests_per_minute': 0, 'max_retries': 10, 'max_retry_wait': 10.0, 'sleep_on_rate_limit_recommendation': True, 'concurrent_requests': 10}

SUCCESS: Local Search Response: The provided text does not contain any data. To help you, I would need specific data or information to analyze or interpret.
```
