### ISSUE TITLE
Server name and port

### ISSUE THREAD

**Issue by bzhanghh** [severian42/GraphRAG-Ollama-UI#28]
How to change Gradio startup server name and port? I tried many methods like add params in demo.launch() and set env variables but all failed. I want to change to http://0.0.0.0:8100

**Comment by rickywu** [comment]
do you find method?

**Comment by bzhanghh** [comment]
> do you find method?

Ya, change the env variables and launch by using python app.py instead of gradio.

**Comment by rickywu** [comment]
> > do you find method?
> 
> Ya, change the env variables and launch by using python app.py instead of gradio.

which var? I didn't find in sample evn file

**Comment by bzhanghh** [comment]
> > > do you find method?
> > 
> > 
> > Ya, change the env variables and launch by using python app.py instead of gradio.
> 
> which var? I didn't find in sample evn file

Set linux env variables GRADIO_SERVER_PORT and GRADIO_SERVER_NAME. I think you can also try to launch by using params like python app.py --host 0.0.0.0 --port ****

**Comment by rickywu** [comment]
Yes, I foiund it, thanks
