### ISSUE TITLE
GRAPHRAG_API_KEY

### ISSUE THREAD

**Issue by aviranmz** [severian42/GraphRAG-Ollama-UI#4]
when running locally it searching for :
GRAPHRAG_API_KEY

**Comment by severian42** [comment]
Hey! Great catch, thanks for calling this out. There should be (or you may have to create) an .env file within the ./ragtest dir. The API key is just a dummy so you can put only GRAPHRAG_API_KEY=12345 in the .env file amd it should just pass it through

**Comment by severian42** [comment]
Hey! Great catch, thanks for calling this out. There should be (or you may have to create) an .env file within the ./ragtest dir. The API key is just a dummy so you can put only GRAPHRAG_API_KEY=12345 in the .env file and it should just pass it through
